### ISSUE TITLE
Login flag is wrong

### ISSUE THREAD

**Issue by bogdumi** [jedevc/HackTheMidlandsCTF19#1]
the flag for login is htmspeektome, not HTM{SPEEKTOME}. trust me, i tried it repeteadly

**Comment by jedevc** [comment]
Both of them were allowed, and you could submit either, which people did ☺️

**Comment by jedevc** [comment]
Welp. I feel stupid now. I went and checked, and turned out yes, I am incompetent and that flag was not allowed. I'll fix it on the writeup.
